---
title: "Exercise 02"
subtitle: Evidence for "textbook" findings
---

## Dates {-}

Due: [Friday, September 13](../schedule.qmd#friday-september-13{.orange_due}.

## Goals {-}

This exercise involves evaluating the base of evidence that supports a particular finding reported in a psychology textbook.

## Assignment {-}

You may work with one other person if you wish. 

Your goal is to evaluate whether the base of evidence that supports a finding in one of your textbooks.
That base of evidence involves several components: the number, quantity, and quality of studies that replicated the original finding; the clarity of the methods description; the availability of shared data; and so on.

1. Choose a finding from one of your psychology textbooks.
2. Find the primary citation or citation(s) that support the claim. If there is more than one, pick the earliest citation for a finding.
3. Use the rubric described in [@Carey2020-ut] to read the paper you chose.
4. Extract from the paper the main *claims*, statements in the text that describe the results, and the *display items*, the tables or figures that support the author(s) arguments for their claims.
5. Create a table summarizing the main claim(s)^[1], your evaluation about whether they are causal or descriptive^[2], and the evidence that supports them.

| Claim | Causal or Descriptive | Evidence |
|-------|-----------------------|----------|
| "Cheetos are the best thing since sliced bread." (pp. 24, para 3) | Descriptive | 1) Figure 1 shows that snack fans rate Cheetos higher than sliced bread. 2) "Mean ratings for Cheetos are higher than those for sliced bread, t(56)=3.58, p<.05" (pp. 15, para 1) |
| "Eating Cheetos before bedtime causes cancer." | Causal | Table 1 shows cancer rates for bedtime Cheetos- vs. non-Cheetos-eating people |

6. Look up your paper on Google Scholar. How many citations does the original paper have? Do any of the citations to the original paper appear to be replication studies?

::: {.callout-tip}

You might filter your original search to see if "replication" is in the title or abstract.

:::

7. Does the paper include shared data?
9. What is your opinion about the strength of the accumulated evidence for the finding(s). Make sure to justify your arguments.

## Submit {-}

A 2-3 page (double-spaced) paper describing your findings in Microsoft Word format using the following file-naming convention:

`<lastname>-<firstname>-PSYCH490.012-ex02.docx`, where you substitute your last name for <lastname> and your first name for <firstname>.
If there are two authors, use both of your last names.
If Dr. Gilmore was submitting a paper, it would look like this: `gilmore-rick-PSYCH490.012-ex02.docx`.

Here is the Canvas dropbox for the assignment:

<https://psu.instructure.com/courses/2280122/assignments/15452006>

Please use the APA format for your paper.
I found the following template document that would be a very good start:

<https://docs.google.com/document/d/1IIKwtH7eVXIkQMz4FwMuKol6hMDT3ra9/copy>

^[1]: Limit yourself to three (3) claims even if the paper makes more.
[^2]: From [@BITSS-ACRE-scoping], "*Causal claim*: a claim is causal if it can be summarize using causal language. This language can be characterize by the following structure: “The paper estimates the effect of a variable X on outcome Y for population P, using method M”. For example: “This paper investigates the impact of bicycle provision (X) on secondary school enrollment (Y) among young women in Bihar/India (P), using a Difference in Difference approach (M). *Descriptive/predictive claim*: a claim is descriptive or predictive if it can be summarize using descriptive or predictive language. language can be characterize by the following structure: “The paper estimates the value of a variable Y (estimated or predicted) for population P under dimensions X (optional) using method M”. For example, “Drawing on a unique Swiss data set (P) and exploiting systematic anomalies in countries’ portfolio investment positions (M), I find that around 8% of the global financial wealth of households is held in tax havens (Y).”
