---
title: "Exercise 04"
subtitle: "Alleged violations of scientific integrity"
---

## Dates {-}

Due: [Friday, October 4](../schedule.qmd#friday-october-04){.orange_due}.

## Goals {-}

The integrity of individual scientists and teams of scientists can lend credence to or undermine scientific methods and findings.
In this exercise, we will explore some of the mechanisms by which violations of scientific integrity come to light.

## Assignment {-}

Choose a case where violations of scientific integrity have been alleged.
Use at least two of the following sources.

- A case study relating to a violation of scientific integrity as reported to the U.S. National Institutes of Health (NIH) Office of Research Integrity ([ORI](https://ori.hhs.gov/)).
- A report about a violation of scientific integrity from the [Retraction Watch](https://retractionwatch.com/) database.
- A post or posts on the [Data Colada site](http://datacolada.org).
- A report in a newspaper or scientific journal.

Describe the allegations, focusing on answering the following questions:

1. What specific violation or violations were alleged?
2. Why are the alleged behavior(s) considered a violation of scientific integrity?
3. What are/were the consequences to the people involved?
4. What could be done to reduce the likelihood that similar alleged violations of scientific integrity occur in the future?

## Submit {-}

In a short (2-3 pp double-spaced report) discuss your answers to these questions and how the two cases are similar or differ from one another.

Please use the APA format for your paper.
Remember the following template document is a good place to start:

<https://docs.google.com/document/d/1IIKwtH7eVXIkQMz4FwMuKol6hMDT3ra9/copy>

## Tips {-}

- I recommend using the five-paragraph essay format for all of your writing assignments in this class. Here is one description of it: <https://www.grammarly.com/blog/five-paragraph-essay/>. You can vary from this format as you gain experience, but if you're struggling, this is a winning structure.
- Give your essay a title.
- Write an introductory paragraph with a clear thesis statement. Here's an example: "In this essay, I describe an allegation of scientific misconduct by Dr. Dietrich Stapel that led to a paper retraction from the journal X. In doing so, I describe the consequences for Dr. Stapel's career in science and responses the scientific community has made to make similar situations less likely in the future."
- Write two or more paragraphs in the body of your essay. Each paragraph should describe a separate topic.
- Write a short concluding paragraph where you summarize your key points.