---
title: "Reading a paper; evaluating its claims"
subtitle: "2024-09-06 Fri"
---

# Overview

## Announcements

- [Due]{.orange_due}
    - [Exercise 01: Reading a scientific paper](../exercises/ex01-read-a-scientific-paper.qmd)

## Last time...

- Repetition/replication $\rightarrow$ trust
- Social character of science can lead researchers astray (Ritchie)
  - As Feymann would say "Fool ______s"
- Scientific communication is "anachronistic" [@Nosek2012-al]

---

:::{.incremental}
- Do you think all research scholarship should be open access (free to anyone)?
    - Who should pay for the costs of publication, maintaining the data?
    - What's wrong with enterprising people making a living by providing these services?
:::

## Today

**Work Session: Reading a paper; Evaluating its claims**

- [Assignment]{.green_assigned}
    - [Exercise 02: Textbook Findings](../exercises/ex02-textbook-findings.qmd)
    
# Survey 01

# Evaluating textbook claims

# Next time

## Monday, September 09

*Scientific norms and counter-norms*

- Read
    - [@Merton1973-vf]. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170713).
    - [@Mitroff1974-pp]. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170712).
- [Assignment]{.green_assigned}
    - Complete (anonymous) [survey](https://forms.gle/reRw9sYUzsYHUsqz9) on scientific norms and counter-norms. **No write-up**.

# Resources

## References
