---
subtitle: "2024-10-04 Fri"
title: "Work session: Exercise 05 and Final Project proposals"
---

# Prelude

## Plot your data!

{{< video https://youtu.be/DbJyPELmhJc?si=8ZQhHTmpPzp-pi3Z width="100%" height="70%" >}}

@Matejka2017-kp

# Overview

## Announcements

- [Due]{.orange_due}
    - [Exercise 04: Violations of scientific integrity](../exercises/ex04-scientific-integrity.qmd)
    
## On *p*-values

>P-values can indicate how incompatible the data are with a specified statistical model. [@Wasserstein2016-kl]

- (Improved) [vocabulary](wk06-2024-09-30-p-values.qmd#vocabulary)
- We have to pick a statistical model (e.g., normal distribution or *t* distribution, or...) for our comparison
- What if our data don't fit the model?

## Last time...

- Do you sympathize with Stapel? Why or why not?
- Have you been in situations like Stapel describes where you have been asked to make a messy and complicated problem simpler?
- Do you think that academic science is becoming a business? Why or why not?
- Why is "massaging of data" or selective reporting of experiments a problem?
- Were the punishments in these cases fair and just or unfair and unjust? Why or why not?

## Today

*Work session: P-hacking & Final project proposals*

- [Assignment]{.green_assigned}
    - [Exercise 05: P-hack your way to scientific glory](../exercises/ex05-p-hacking.qmd) write-up.
- Work session
    - [Final project proposals](../exercises/final-project.qmd), [due Friday, October 13]{.orange_due}.

# Next time

*Retraction and scientific integrity*

*On Zoom*: <https://psu.zoom.us/my/rogilmore>. Check-in for attendance. Join from anywhere convenient to you.

- Read
    - @Brainerd2018-iy
    
# Resources

## References
