## Schedule

### Week 1: August 26-30 {- #week-01}

#### Monday, August 26 {-}

*Introduction to the course: Why trust science?*

- Read
  - (Recommended) @Oreskes2017, Chapter 1, pp. 55-68 | [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170717).
- (Extra credit) Complete [Survey 01 on Trust in Science and Scientists](https://forms.gle/471gpq6XXXq9iG9C8)
- [Class notes](notes/wk01-2024-08-26-intro.qmd)

::: {.callout-tip}
To earn 3 extra credit points for completing the survey, send the TA one of the following:

1. The date and time you completed the survey in the following format: "7/30/2024 12:20:23"
2. A special code or phrase that is likely to be unique to you but doesn't contain identifiable information.
:::

#### Wednesday, August 28 {-}

- Wrap up on ["Why trust science"](notes/wk01-2024-08-26-intro.qmd#trust-in-science)

*Don't Fool Yourself*

- Read
    - @Feynman1974-ld.
    - (Recommended) @sagan-1996-baloney, Chapter 12, The Fine Art of Baloney Detection. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170710)
- [Class notes](notes/wk01-2024-08-28-no-foolin.qmd)

#### Friday, August 30 {-}

*Work Session: How to read a scientific paper*

- Read
    - @Carey2020-ut
    - @Ruben2016-om (for fun)
- [Assignment]{.green_assigned}
    - [Exercise 01: Reading a scientific paper](exercises/ex01-read-a-scientific-paper.qmd)
- [Class notes](notes/wk01-2024-08-30-how-to-read.qmd)

### Week 2: September 2-6 {- #week-02}

#### Monday, September 02 {-}

**NO CLASS, LABOR DAY**

#### Wednesday, September 04 {-}

*How science works (or should)*

- Read
    - @Ritchie2020-fm, Chapter 1. [Alternate link to PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170709).
    - @Nosek2012-al. [Alternate link to PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170711)
- [Assignment]{.green_assigned}
    - Complete (anonymous, extra credit) [survey](https://forms.gle/zGm5vZsPrTxwRDVR7) on scientific norms and counter-norms. **No write-up**.
- [Class notes](notes/wk02-2024-09-04-how-science-works.qmd)

#### Friday, September 06 {-}

<!-- Adam not in class! -->

**Work Session: Reading a paper; Evaluating its claims**

- [Due]{.orange_due}
    - [Exercise 01: Reading a scientific paper](exercises/ex01-read-a-scientific-paper.qmd)
- [Assignment]{.green_assigned}
    - [Exercise 02: Textbook Findings](exercises/ex02-textbook-findings.qmd), [due Friday, September 20]{.orange_due}
- [Class notes](notes/wk02-2024-09-06-claims.qmd), due 

### Week 3: September 9-13 {- #week-03}

#### Monday, September 09

*Scientific norms and counter-norms*

- Read
    - @Merton1973-vf. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170713).
    - @Mitroff1974-pp. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170712).
- [Assignment]{.green_assigned}
    - Complete (anonymous) [survey](https://forms.gle/reRw9sYUzsYHUsqz9) on scientific norms and counter-norms. **No write-up**.
- [Class notes](notes/wk03-2024-09-09-norms-counternorms.qmd)

#### Wednesday, September 11 {-}

*Adherence to norms and counter-norms*

- Read
    - @Kardash2012-kq
    - @Macfarlane2008-tc
<!-- - Skim -->
<!--     - @Anderson2010-rl. -->
<!--     - @Kim2018-tr]. -->
- [Class notes](notes/wk03-2024-09-11-adherence-to-norms.qmd)

#### Friday, September 13 {-}

*Work session: Norms and counter-norms*

- Survey 02: [From raw data to results](surveys/survey-02.qmd)
- [Assignment]{.green_assigned}
    - [Exercise 03: Norms and counter-norms](exercises/ex03-norms-counternorms.qmd), [due Friday, September 27]{.orange_due}
- [Class notes](notes/wk03-2024-09-13-work-session-norms.qmd)

### Week 4: September 16-20 {- #week-04}

#### Monday, September 16 {-}

*A replication crisis (or not)*

- Read
    - @Ritchie2020-fm, Chapter 2. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170706).
    - @Begley2012-cr.
- [Class notes](notes/wk04-2024-09-16-replication-crisis.qmd)

#### Wednesday, September 18 {-}

*Replication attempt: The "Lady Macbeth Effect"*

- Read
    - @Zhong2006-nf
    - @Earp2014-ek
- [Class notes](notes/wk04-2024-09-18-replication-lady-macbeth.qmd)

#### Friday, September 20 {-}

*Wrap-up on 'Macbeth effect' replication*

- Read
  - @Earp2014-ek
- [Due]{.orange_due}
    - [Exercise 02: Textbook Findings](exercises/ex02-textbook-findings.qmd)
- [Class notes](notes/wk04-2024-09-20-work-session-R.qmd)

### Week 5: September 23-27 {- #week-05}

#### Monday, September 23 {-}

*Priming effect: Original study*

- Read
    - @Bargh1996-yv; [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170715)
- [Class notes](notes/wk05-2024-09-23-priming.qmd)

#### Wednesday, September 25 {-}

*Priming effect: Replication study*

- Read
    - @Doyen2012-ib
    - review @Bargh1996-yv; [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170715)
- [Class notes](notes/wk05-2024-09-25-priming-replication.qmd)

<!-- *What R are we talking about?* -->

<!-- - Read -->
<!--     - [@Fidler2021-xn], especially sections 1, 2, and 3.1-3.2. -->
<!--     - (Skim) [@Nosek2022-hv] or [@goodman_what_2016] -->
<!-- - [Class notes](notes/wk05-2024-09-25-what-r.qmd) -->

#### Friday, September 27 {-}

*Work session: Scientific integrity & Final project proposals*

- [Assignment]{.green_assigned}
    - [Exercise 04: Violations of scientific integrity](exercises/ex04-scientific-integrity.qmd), [due Friday, October 4]{.orange_due}
    - [Final project proposals](exercises/final-project.qmd), [due Friday, October 18]{.orange_due}.
- [Due]{.orange_due}
    - [Exercise 03: Norms and counter-norms write-up](exercises/ex03-norms-counternorms.qmd)
- [Class notes](notes/wk05-2024-09-27-work-integrity.qmd)

### Week 6: September 30 - October 4 {- #week-06}

#### Monday, September 30

*Mind your p's*

- Read
  - @Denworth2019-uh
- [Class notes](notes/wk06-2024-09-30-p-values.qmd)

#### Wednesday, October 02 {-}

*Fraud & misconduct*

- Read
    - @Ritchie2020-fm, Chapter 3
    - @Bhattacharjee2013-rw, [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170718)
    - (Skim) @Levelt2012-ap
    - (Skim) @Carpenter2012-qy
- [Class notes](notes/wk06-2024-10-02-fraud-misconduct.qmd)

#### Friday, October 04 {-}

*Work session: P-hacking & Final project proposals*

- [Due]{.orange_due}
    - [Exercise 04: Violations of scientific integrity](exercises/ex04-scientific-integrity.qmd)
- [Assignment]{.green_assigned}
    - [Exercise 05: P-hack your way to scientific glory](exercises/ex05-p-hacking.qmd) write-up.
- Work session
    - [Final project proposals](exercises/final-project.qmd), [due Friday, October 18]{.orange_due}.
- [Class notes](notes/wk06-2024-10-04-work-session.qmd)

### Week 7: October 7-11 {- #week-07}

#### Monday, October 07 {-}

<!-- Gilmore in Chicago. -->

*Retraction and scientific integrity*

*On Zoom*: <https://psu.zoom.us/my/rogilmore>. Check-in for attendance. Join from anywhere convenient to you.

- Read
    - @Brainerd2018-iy
- [Class notes](notes/wk07-2024-10-07-retraction.qmd)
    
#### Wednesday, October 09 {-}

**NO CLASS**

#### Friday, October 11 {-}

*Questionable research practices*

- Read
    - @simmons_false-positive_2011
- Watch
    - @Ngiam2020-ln
- Bring
    - Draft [Exercise 05: P-hack your way to scientific glory](exercises/ex05-p-hacking.qmd) for discussion.
- [Class notes](notes/wk07-2024-10-11-qrps.qmd)

### Week 8: October 14-18 {- #week-08}

#### Monday, October 14 {-}

*Work Session: P-hacking and Final Project Proposals*

- [Due]{.orange_due}
    - [Exercise 05: P-hack your way to scientific glory](exercises/ex05-p-hacking.qmd) write-up.
- Work session
    - [Final project proposals](exercises/final-project.qmd), [due Friday, October 18]{.orange_due}.
- [Class notes](notes/wk08-2024-10-14-p-hacking.qmd)

#### Wednesday, October 16 {-}

*Prevalence of QRPs*

- Read
    - @John2012-tk
- [Class notes](notes/wk08-2024-10-16-qrp-prevalence.qmd)

#### Friday, October 18 {-}

*File drawer effect & Work Session: Alpha, Power, Effect Sizes, & Sample Size*

- Read
    - (Skim) @Rosenthal1979-zi. [PDF on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170719)
    - (Optional) @Franco2014-yu
- [Assignment]{.green_assigned}
    - [Exercise 06: Alpha, Power, Effect Sizes, & Sample Size](exercises/ex06-apes.qmd), [final version due Wednesday, October 30]{.orange_due}
- [Due]{.orange_due}
    - [Final project](exercises/final-project.qmd) proposal
- [Class notes](notes/wk08-2024-10-18-file-drawer.qmd)
- [Self Test 01](exercises/st-01.qmd)

### Week 9: October 21-25 {- #week-09}

#### Monday, October 21 {-}

*Negligence*

- Read
    - @Nuijten2015-ul
    - (skim) @Szucs2017-fc
- [Class notes](notes/wk09-2024-10-21-negligence.qmd)

#### Wednesday, October 23 {-}

*Hype*

- Watch & discuss
    - [@Cuddy2012-zx](https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are)
- Read
    - @Carney2010-gq, [file on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170721)
    - (Optional) @Ranehill2015-dj, [file on Canvas](https://psu.instructure.com/courses/2350148/files/folder/readings?preview=165170720)
- [Class notes](notes/wk09-2024-10-23-hype.qmd)
 
#### Friday, October 25 {-}

*Hype, continued*

- Discuss @Cuddy2012-zx, @Carney2010-gq, and @Ranehill2015-dj

*Work session: Alpha, Power, Effect Sizes, & Sample Size & Replication*

- [Discuss draft]{.orange_due}
    - [Exercise 06: Alpha, Power, Effect Sizes, & Sample Size](exercises/ex06-apes.qmd) write-up
- [Assignment]{.green_assigned}
    - [Exercise 07: Replication](exercises/ex07-replication.qmd), [due Friday, November 8]{.orange_due}
- [Class notes](notes/wk09-2024-10-25-work-session.qmd)

### Week 10: October 28 - November 1 {- #week-10}

#### Monday, October 28 {-}

*Solutions*

- Read
    - @munafo_manifesto_2017
    - @Begley2013-vm
- [Class notes](notes/wk10-2024-10-28-solutions.qmd)
    
#### Wednesday, October 30 {-}

*Changing journal policies*

- Read
    - @nosek_promoting_2015
    - @Gilmore2020-sl
    - @Srcd2019-hg
- [Class notes](notes/wk10-2024-10-30-journal-practices.qmd)
- [Final version due]{.orange_due}
    - [Exercise 06: Alpha, Power, Effect Sizes, & Sample Size](exercises/ex06-apes.qmd) write-up

#### Friday, November 01 {-}

*Large-scale replication studies*

- Read
    - @collaboration_estimating_2015
- [Class notes](notes/wk10-2024-11-01-replication.qmd)
- Complete (extra credit)
    - [Questionnaire](https://forms.gle/gGAVmWjCHRVDekMo6) based on @Chopik2018-wx. 
    
*Work Session: Final Projects*

### Week 11: November 4-8 {- #week-11}

#### Monday, November 04 {-}

*Meta-analysis*

- Read
    - @Wilson2014-ol
- [Class notes](notes/wk11-2024-11-04-meta-analysis.qmd)

#### Wednesday, November 06 {-}

*Many analysts*

- Read
    - @Silberzahn2018-st
- [Class notes](notes/wk11-2024-11-06-many-analysts.qmd)

#### Friday, November 08 {-}

*Work Session: Final Projects*

- [Due]{.orange_due}
    - [Exercise 07: Replication](exercises/ex07-replication.qmd)
- [Class notes](notes/wk11-2024-11-08-work-session.qmd)

### Week 12: November 11-15 {- #week-12}

#### Monday, November 11 {-}

*Preregistration*

- Read
    - @Nosek2018-jk
    - @Ledgerwood2018-sn or @Goldin-Meadow2016-mc
    - (Optional) @Claesen2021-ae
- Explore
    - [clinicaltrials.gov](https://clinicaltrials.gov/)
- [Class notes](notes/wk12-2024-11-11-prereg.qmd)

#### Wednesday, November 13 {-}

*Data sharing*

- Read
    - @Houtkoop2018-tl
    - @Tenopir2020-mq
    - (Optional) @GilmoreAdolph2017
    - (Optional) @Meyer2018-vk
    - (Optional) [@National_Institutes_of_Health_undated-it](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-21-013.html)
- [Class notes](notes/wk12-2024-11-13-data-sharing.qmd)

#### Friday, November 15 {-}

*Work Session: Final Projects*

- [Final project survey]{.green_assigned}
    - Please complete the [final project survey](https://forms.gle/vtdJ82Y7AjgU15VA9) by [Friday, November 22]{.orange_due}
- [Class notes](notes/wk12-2024-11-15-work-session.qmd)

### Week 13: November 18-22 {- #week-13}

#### Monday, November 18 {-}

*Materials, code, & protocol sharing*

- Read
    - @Soska2021-mh
    - @Gilroy2019-bf
- Explore
    - [protocols.io](https://www.protocols.io/)
    - [Journal of Visualized Experiments (JOVE)](https://www.jove.com/)
- [Class notes](notes/wk13-2024-11-18-materials-sharing.qmd)

#### Wednesday, November 20 {-}

*Open science tools*

- Read
    - @Kathawalla2021-tk
    - @Chopik2018-wx
    - (Optional) @Cruwell2019-nz
- Explore
    - @FORRT_undated-pl
- Complete (optional)
    - [Questionnaire](https://forms.gle/gGAVmWjCHRVDekMo6) based on @Chopik2018-wx. Results are [here](surveys/survey-03.qmd).
- [Class notes](notes/wk13-2024-11-20-open-sci-tools.qmd)

#### Friday, November 22 {-}

*Work session: Data sharing & Final Projects*

- **Hybrid session**: In-person and on Zoom (<https://psu.zoom.us/my/rogilmore>)

- [Assignment distributed]{.green_assigned}
    - [Exercise 08: Data and materials sharing](exercises/ex08-sharing.qmd)
- [[Final project survey](https://forms.gle/vtdJ82Y7AjgU15VA9)]{.orange_due}
- [Class notes](notes/wk13-2024-11-22-work-session.qmd)

### November 25-29 *Thanksgiving Break*

### Week 14: December 2-6 {- #week-14}

#### Monday, December 2 {-}

*In-class final project work day*

#### Wednesday, December 4 {-}

*In-class final project work day*

#### Friday, December 6 {-}

*Project presentations*

- [Schedule](surveys/presentation-schedule.qmd#day-1-friday-december-6-2024)
- [Assignment Due]{.orange_due}
    - [Exercise 08: Data and materials sharing](exercises/ex08-sharing.qmd)

### Week 15: December 9-13 {- #week-15}

#### Monday, December 9 {-}

*Project presentations*

- [Schedule](surveys/presentation-schedule.qmd#day-2-monday-december-9-2024)

#### Wednesday, December 11 {-}

*Project presentations*

- [Schedule](surveys/presentation-schedule.qmd#day-3-wednesday-december-11-2024)

#### Friday, December 13 {-}

*Our open science future*

- [Class notes](notes/wk15-2024-12-13-open-sci-future.qmd)
  
### Finals Week: December 16-20 {- #finals-week}

#### Wednesday, December 18 {-}

- [Due]{.orange_due}
  - [Final project](exercises/final-project.qmd) write-ups due 5:00 PM.
